name: GuicedEE Client Library
on:
  workflow_dispatch:
  push:
jobs:
  GuicedClient:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: ''
      name: 'Guiced Client'
      sonarProjectName: 'GuicedEE_Client'
      sonarOrganization: 'guicedee'
    secrets: inherit