name: Maven Package
on:
  workflow_dispatch:
  push:
jobs:
  GuicedClient:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: ''
      name: 'Guiced Client'
      sonarProjectName: 'GuicedEE_Client'
    secrets: inherit